[package]
name = "msc-thesis-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
xshell = "0.2.6"
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
